# Generated by Django 3.2 on 2021-04-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20, verbose_name='نام برند')),
                ('brand_nationality', models.CharField(max_length=20, verbose_name='ملیت برند')),
                ('model', models.CharField(max_length=20, unique=True, verbose_name='مدل گوشی')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('gold', 'Gold'), ('silver', 'Silver')], max_length=10, verbose_name='رنگ')),
                ('resulation', models.FloatField(verbose_name='سایز صفحه نمایش')),
                ('is_available', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('manufacturer', models.CharField(max_length=20, verbose_name='کشور سازنده')),
            ],
            options={
                'verbose_name': 'موبایل',
                'verbose_name_plural': 'موبایل ها',
            },
        ),
    ]
