# Generated by Django 3.2 on 2021-04-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='وضعیت موجودی'),
        ),
    ]
