# Generated by Django 3.2 on 2021-04-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_alter_mobile_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='color',
            field=models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('gold', 'Gold'), ('silver', 'Silver'), ('blue', 'Blue')], max_length=10, verbose_name='رنگ'),
        ),
    ]
